[package]
name = "file_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"

[profile.release]
opt-level = 3          
debug = false          
lto = true             
codegen-units = 1      
panic = "abort"        

